### ISSUE TITLE
有一些想法

### ISSUE THREAD

**Issue by cairongquan** [KeyleXiao/CreateBabyName#1]
抱歉提了一个issue，对于整个github流程不太熟悉，我想知道作者是不是将名称类似于数据库存在了本地，然后通过用户输入筛选条件，将名称筛选出来。

**Comment by KeyleXiao** [comment]
[Chinese_Names.txt](https://github.com/KeyleXiao/CreateBabyName/blob/main/ConsoleApp1/Chinese_Names.txt) 库文件在这里。你只需要将需要的名字库替换这个文件就可以，名字库在github上能找到很多。

**Comment by cairongquan** [comment]
好的，然后我的想法是基于这个库，做一个基础库，然后结合ai，随机生成名字，并且给名字解释意义这样哈哈

**Comment by KeyleXiao** [comment]
倒是可以，你直接把这个库，喂给ai
